#!/usr/bin/with-contenv bash
# ==============================================================================
# Community Hass.io Add-ons: Phlex
# Runs the NGINX daemon
# ==============================================================================
# shellcheck disable=SC1091
source /usr/lib/hassio-addons/base.sh

# Wait for PHP-FPM to become available
s6-svwait -u -t 5000 /var/run/s6/services/php-fpm

hass.log.info "Starting Phlex..."
exec nginx -g "daemon off;"
