#!/usr/bin/with-contenv bash
# ==============================================================================
# Community Hass.io Add-ons: Phlex
# Runs the PHP-FPM daemon
# ==============================================================================

exec php-fpm7 --nodaemonize
